/*
 * Superfish v1.4.8 - jQuery menu widget
 * Copyright (c) 2008 Joel Birch
 *
 * Dual licensed under the MIT and GPL licenses:
 * 	http://www.opensource.org/licenses/mit-license.php
 * 	http://www.gnu.org/licenses/gpl.html
 *
 * CHANGELOG: http://users.tpg.com.au/j_birch/plugins/superfish/changelog.txt
 */
!function(s){s.fn.superfish=function(a){var o=s.fn.superfish,e=o.c,i=s(['<span class="',e.arrowClass,'"></span>'].join("")),n=function(){var a=s(this),o=t(a);clearTimeout(o.sfTimer),a.showSuperfishUl().siblings().hideSuperfishUl()},r=function(){var a=s(this),e=t(a),i=o.op;clearTimeout(e.sfTimer),e.sfTimer=setTimeout(function(){i.retainPath=s.inArray(a[0],i.$path)>-1,a.hideSuperfishUl(),i.$path.length&&a.parents(["li.",i.hoverClass].join("")).length<1&&n.call(i.$path)},i.delay)},t=function(s){var a=s.parents(["ul.",e.menuClass,":first"].join(""))[0];return o.op=o.o[a.serial],a},h=function(s){s.addClass(e.anchorClass).append(i.clone())};return this.each(function(){var i=this.serial=o.o.length,t=s.extend({},o.defaults,a);t.$path=s("li."+t.pathClass,this).slice(0,t.pathLevels).each(function(){s(this).addClass([t.hoverClass,e.bcClass].join(" ")).filter("li:has(ul)").removeClass(t.pathClass)}),o.o[i]=o.op=t,s("li:has(ul)",this)[s.fn.hoverIntent&&!t.disableHI?"hoverIntent":"hover"](n,r).each(function(){t.autoArrows&&h(s(">a:first-child",this))}).not("."+e.bcClass).hideSuperfishUl();var l=s("a",this);l.each(function(s){l.eq(s).parents("li")}),t.onInit.call(this)}).each(function(){var a=[e.menuClass];!o.op.dropShadows||s.browser.msie&&s.browser.version<7||a.push(e.shadowClass),s(this).addClass(a.join(" "))})};var a=s.fn.superfish;a.o=[],a.op={},a.IE7fix=function(){var o=a.op;s.browser.msie&&s.browser.version>6&&o.dropShadows&&void 0!=o.animation.opacity&&this.toggleClass(a.c.shadowClass+"-off")},a.c={bcClass:"sf-breadcrumb",menuClass:"sf-js-enabled",anchorClass:"sf-with-ul",arrowClass:"menu-arrow",shadowClass:"sf-shadow"},a.defaults={hoverClass:"sfHover",pathClass:"overideThisToUse",pathLevels:2,delay:1e3,animation:{height:"show"},speed:"normal",autoArrows:!1,dropShadows:!1,disableHI:!1,onInit:function(){},onBeforeShow:function(){},onShow:function(){},onHide:function(){}},s.fn.extend({hideSuperfishUl:function(){var o=a.op,e=o.retainPath===!0?o.$path:"";o.retainPath=!1;var i=s(["li.",o.hoverClass].join(""),this).add(this).not(e).removeClass(o.hoverClass).find(">ul").hide();return o.onHide.call(i),this},showSuperfishUl:function(){var s=a.op,o=(a.c.shadowClass+"-off",this.not(".accorChild").addClass(s.hoverClass).find(">ul:hidden"));return a.IE7fix.call(o),s.onBeforeShow.call(o),o.animate(s.animation,s.speed,function(){a.IE7fix.call(o),s.onShow.call(o)}),this}})}(jQuery),$(function(){$(".sf-menu").superfish({autoArrows:!0})});